{% set name = "SCGV" %}
{% set version = "1.0.2" %}
{% set sha256hash = "789ea42eebe58fd7988dd801bfa84636f15da1ea3168992843d6f1a9c4762a5d" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KrasnitzLab/SCGV/archive/{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  entry_points:
    - scgview = scgv.tkmain:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - matplotlib
    - numpy
    - pandas
    - scipy
    - pillow
  run:
    - python
    - setuptools
    - matplotlib
    - numpy
    - pandas
    - scipy
    - pillow
test:
  imports:
    - scgv
  commands:
    - scgview --help

about:
  home: https://github.com/KrasnitzLab/SCGV
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: SCGV is an interacive graphical tool for single-cell genomics data, with emphasis on single-cell genomics of cancer
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
