{% set name = "SCGV" %}
{% set version = "1.0.3" %}
{% set sha256hash = "81016c945809ae230d7d069d0b4d2bda0e464153fb6fe9f4f29bb7d0eb3354af" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KrasnitzLab/SCGV/archive/{{ version }}.tar.gz
  sha256: {{ sha256hash }}
  # path: ../../SCGV
build:
  number: 2
  entry_points:
    - scgview = scgv.tkmain:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - matplotlib <3.0.0
    - numpy
    - pandas
    - scipy
    - pillow
  run:
    - python
    - setuptools
    - matplotlib <3.0.0
    - numpy
    - pandas
    - scipy
    - pillow
test:
  imports:
    - scgv
  commands:
    - scgview --help

about:
  home: https://github.com/KrasnitzLab/SCGV
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: SCGV is an interacive graphical tool for single-cell genomics data, with emphasis on single-cell genomics of cancer
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
