{% set name = "SCGV" %}
{% set version = "1.2.5" %}
{% set sha256hash = "7ba20e272b6e871227efd93e8a6b10b3f05276a121017c9dc38a56fd313f1d21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/KrasnitzLab/SCGV/archive/{{ version }}.tar.gz
  # sha256: {{ sha256hash }}
  path: ../../SCGV
build:
  number: 44
  entry_points:
    - scgview = scgv.qtmain:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python =3.7
    - setuptools
    - matplotlib >=3.1.3, <3.3.0
    - numpy >=1.18.1
    - pandas >=1.0.1
    - scipy >=1.4.1
    - pillow
    - pyqt >=5.9.0
  run:
    - python =>3.7
    - setuptools
    - matplotlib >=3.1.3, <3.3.0
    - numpy >=1.18.1
    - pandas >=1.0.1
    - scipy >=1.4.1
    - pillow
    - pyqt >=5.9.0
# test:
#   imports:
#     - scgv
#   commands:
#     - scgview --help

about:
  home: https://github.com/KrasnitzLab/SCGV
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: SCGV is an interacive graphical tool for single-cell genomics data, with emphasis on single-cell genomics of cancer
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
