{% set name = "SCGV" %}
{% set version = "1.2.6" %}
{% set sha256hash = "7ba20e272b6e871227efd93e8a6b10b3f05276a121017c9dc38a56fd313f1d21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/KrasnitzLab/SCGV/archive/{{ version }}.tar.gz
  # sha256: {{ sha256hash }}
  path: ../../SCGV
build:
  number: 76
  entry_points:
    - scgview = scgv.qtmain:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python =3.7
    - setuptools =52.0.0
  run:
    - python =3.7
    - setuptools =52.0.0
    - matplotlib =3.4.2
    - numpy =1.18.1
    - pandas =1.2.4
    - scipy =1.4.1
    - pillow =8.3.1
    - pyqt =5.9.2

test:
  imports:
    - scgv
  # commands:
  #   - scgview --help

about:
  home: https://github.com/KrasnitzLab/SCGV
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: SCGV is an interacive graphical tool for single-cell genomics data, with emphasis on single-cell genomics of cancer
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
