{% set name = "SCclust" %}
{% set version = "v1.0.1" %}
{% set sha256hash = "68942c5a5fba8e605a8802e41fc95493a057a2dcb69c1a92394ac79ab1914f1a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: 
    - 'https://github.com/KrasnitzLab/SCclust/archive/{{ version }}.tar.gz'
  sha256: {{ sha256hash }}
  # path: ../SCclustSource
  # path: ../../SCclust
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base >=3.5.1
    - r-testthat
    - r-assertthat
    - bioconductor-dnacopy=1.52
  run:
    - r-base >=3.5.1
    - r-testthat
    - r-assertthat
    - bioconductor-dnacopy=1.52
test:
  commands:
    - '$R -e "library(SCclust)"'
about:
  home: 'https://github.com/KrasnitzLab/SCclust'
  license: 'MIT'
  summary: 'Segmentation and Clustering of Single Cell Sequencing Copy Number Profiles'
