{% set name = "SCclust" %}
{% set version = "1.0.3" %}
# {% set sha256hash = "7a2698a86d29b874202980177db8580b779f4a973a64c317b4b5a9ae63f8480c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  # url: 
  #   - 'https://github.com/KrasnitzLab/SCclust/archive/{{ version }}.tar.gz'
  # sha256: {{ sha256hash }}
  # path: ../SCclustSource
  path: ../../SCclust
build:
  number: 5
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base =3.6.2
    - r-testthat
    - r-assertthat
    - bioconductor-dnacopy
  run:
    - r-base =3.5.1
    - r-testthat
    - r-assertthat
    - bioconductor-dnacopy
test:
  commands:
    - '$R -e "library(SCclust)"'
about:
  home: 'https://github.com/KrasnitzLab/SCclust'
  license: 'MIT'
  summary: 'Segmentation and Clustering of Single Cell Sequencing Copy Number Profiles'
