{% set name = "SCclust" %}
{% set version = "1.0.7" %}
# {% set sha256hash = "7a2698a86d29b874202980177db8580b779f4a973a64c317b4b5a9ae63f8480c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  # url: 
  #   - 'https://github.com/KrasnitzLab/SCclust/archive/{{ version }}.tar.gz'
  # sha256: {{ sha256hash }}
  # path: ../SCclustSource
  path: ../../SCclust
build:
  number: 68
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base =3.6.1
  run:
    - r-base =3.6.1
    - r-testthat =2.1.1
    - r-assertthat =0.2.1
    - r-futile.logger =1.4.3
    - bioconductor-dnacopy =1.66.0
test:
  commands:
    - '$R -e "library(SCclust)"'
about:
  home: 'https://github.com/KrasnitzLab/SCclust'
  license: 'MIT'
  summary: 'Segmentation and Clustering of Single Cell Sequencing Copy Number Profiles'
