{% set name = "sgains" %}
{% set version = "2.1.0" %}
{% set sha256hash = "c5e5f2f951e3dd46b6211e5d42b74819984dc24d8cc386123d9801b95296cd59" %}


package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  # url: https://github.com/KrasnitzLab/sgains/archive/{{version}}.tar.gz
  # sha256: {{ sha256hash }}
  path: ../../sgains
build:
  number: 66
  entry_points:
    - sgains-tools = sgains.tool:main
    - sg = sgains.tool:main

  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python =3.7.6
    - setuptools =52.0.0
  run:
    - python =3.7.6
    - setuptools =52.0.0
    - numpy =1.18.1
    - pandas =1.2.4
    - scipy =1.4.1
    - pysam =0.9.1
    - htslib =1.3.1
    - samtools =1.3.1
    - biopython =1.78
    - termcolor =1.1.0
    - python-box =5.4.1
    - cerberus =1.3.2
    - bowtie =1.3.0
    - hisat2 =2.1.0
    - bwa =0.7.17
    - fastx_toolkit =0.0.14
    - scclust =1.0.7
    - pyyaml =5.4.1
    - dask =2021.8.0
    - dask-jobqueue =0.7.3
  test:
    imports:
      - sgains
    commands:
      - sgains-tools --help
      - sgains-tools scclust --help

about:
  home: https://github.com/KrasnitzLab/sgains
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: 'Sparse Genomic Analysis of Individual Nuclei by Sequencing (s-GAINS)'
  description: 'Sparse Genomic Analysis of Individual Nuclei by Sequencing (s-GAINS)'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - lchorbadjiev
