{% set name = "sgains" %}
{% set version = "1.0.3" %}
{% set sha256hash = "c5e5f2f951e3dd46b6211e5d42b74819984dc24d8cc386123d9801b95296cd59" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KrasnitzLab/sgains/archive/{{version}}.tar.gz
  sha256: {{ sha256hash }}
  # path: ../../sgains
build:
  number: 3
  entry_points:
    - sgains-tools = sgains.cli:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.7
    - setuptools
    - numpy =1.18.1
    - pandas =1.0.1
    - scipy =1.4.1
    - pysam
    - biopython
    - termcolor
    - python-box
    - bowtie >=1.2.2,<2
    - hisat2
    - r-base >=3.6.2
    - scclust >=1.0.3
    - scgv >=1.2.2
    - pyyaml
  run:
    - python >=3.7
    - setuptools
    - numpy =1.18.1
    - pandas =1.0.1
    - scipy =1.4.1
    - pysam
    - biopython
    - termcolor
    - python-box
    - bowtie >=1.2.2,<2
    - hisat2
    - r-base >=3.6.1
    - scclust >=1.0.3
    - scgv >=1.2.2
    - pyyaml
    - openssl =1.0.*
    - htslib
    - samtools
  test:
    imports:
      - sgains
    commands:
      - sgains-tools --help
      - sgains-tools scclust --help

about:
  home: https://github.com/KrasnitzLab/sgains
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: 'Sparse Genomic Analysis of Individual Nuclei by Sequencing (s-GAINS)'
  description: 'Sparse Genomic Analysis of Individual Nuclei by Sequencing (s-GAINS)'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - lchorbadjiev
