{% set name = "sgains" %}
{% set version = "1.0.0" %}
{% set sha256hash = "2f6b64d249c609932a8e1596b83d7c385c61c949f2c0cd36b9a6dbfeee12d4be" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KrasnitzLab/sgains/archive/v{{version}}.tar.gz
  sha256: {{ sha256hash }}
  # path: ../../sgains
build:
  number: 9
  entry_points:
    - sgains-tools = sgains.cli:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.6
    - setuptools
    - numpy
    - pandas
    - scipy
    - pysam
    - biopython
    - termcolor
    - python-box
    - bowtie >=1.2.2,<2
    - r-base >=3.5.1
    - scclust >=1.0.1
    - pyyaml
  run:
    - python >=3.6
    - setuptools
    - numpy
    - pandas
    - scipy
    - pysam
    - biopython
    - termcolor
    - python-box
    - bowtie >=1.2.2,<2
    - r-base >=3.5.1
    - scclust >=1.0.1
    - pyyaml
  test:
    imports:
      - sgains
    commands:
      - sgains-tools --help
      - sgains-tools scclust --help

about:
  home: https://github.com/KrasnitzLab/sgains
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: 'Sparse Genomic Analysis of Individual Nuclei by Sequencing (s-GAINS)'
  description: 'Sparse Genomic Analysis of Individual Nuclei by Sequencing (s-GAINS)'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - lchorbadjiev
